# Generated by Django 5.1 on 2024-08-24 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
                ("street", models.CharField(max_length=50, verbose_name="Улица")),
                ("house", models.CharField(max_length=10, verbose_name="Дом/строение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        choices=[
                            ("завод", "завод"),
                            ("розничная сеть", "розничная сеть"),
                            ("ИП", "ИП"),
                        ],
                        max_length=20,
                        verbose_name="звено",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="предыдущий по иерархии участник сети",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_link=True,
                        related_name="customer",
                        to="participants.participant",
                        verbose_name="поставщик",
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[("0", "0"), ("1", "1"), ("2", "2")],
                        max_length=3,
                        null=True,
                        verbose_name="уровень",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник",
                "verbose_name_plural": "участники",
                "ordering": ["-pk"],
            },
        ),
    ]
